[versions]
targetSdk = "31"
compileSdk = "33"
minSdk = "21"
wearMinSdk = "25"

kotlin = "1.8.10" # https://kotlinlang.org/docs/releases.html#release-details
agp = "7.4.0" # https://developer.android.com/studio/releases/gradle-plugin
realm = "1.5.2" # https://github.com/realm/realm-kotlin
detekt = "1.22.0" # https://github.com/detekt/detekt

compose = "1.3.3" # https://developer.android.com/jetpack/androidx/releases/compose-ui
composeCompiler = "1.4.2" # https://developer.android.com/jetpack/androidx/releases/compose-compiler
# https://developer.android.com/jetpack/androidx/releases/compose-kotlin
wearCompose = "1.1.1" # https://developer.android.com/jetpack/androidx/releases/wear-compose
coroutines = "1.6.4" # https://github.com/Kotlin/kotlinx.coroutines
datastore = "1.0.0" # https://developer.android.com/jetpack/androidx/releases/datastore
koin = "3.3.2" # https://github.com/InsertKoinIO/koin
lifecycle = "2.5.1" # https://developer.android.com/jetpack/androidx/releases/lifecycle
core = "1.9.0" # https://developer.android.com/jetpack/androidx/releases/core
glance = "1.0.0-alpha05" # https://developer.android.com/jetpack/androidx/releases/glance

[libraries]
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
realmGradle = { module = "io.realm.kotlin:gradle-plugin", version.ref = "realm" }
detektGradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detektCompose = "com.twitter.compose.rules:detekt:0.0.26" # https://github.com/twitter/compose-rules

realmKotlin = { module = "io.realm.kotlin:library-base", version.ref = "realm" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
#compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material = "androidx.compose.material3:material3:1.0.1" # https://developer.android.com/jetpack/androidx/releases/compose-material3
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

compose-activity = "androidx.activity:activity-compose:1.6.1" # https://developer.android.com/jetpack/androidx/releases/activity
compose-constraint = "androidx.constraintlayout:constraintlayout-compose:1.0.1" # https://developer.android.com/jetpack/androidx/releases/constraintlayout

compose-uiTest = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-uiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

composeWear-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearCompose" }
composeWear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearCompose" }
composeWear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearCompose" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines"}

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version = "3.4.1" } # https://github.com/InsertKoinIO/koin

androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "core" }

glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
#glance-wear-tiles = { module = "androidx.glance:glance-wear-tiles", version.ref = "glance" }


androidx-annotation = "androidx.annotation:annotation:1.5.0"        # https://mvnrepository.com/artifact/androidx.annotation/annotation
androidx-appcompat = "androidx.appcompat:appcompat:1.6.0"           # https://developer.android.com/jetpack/androidx/releases/appcompat
androidx-wear = "androidx.wear:wear:1.2.0"                          # https://developer.android.com/jetpack/androidx/releases/wear
junit = "junit:junit:4.13.2"
material = "com.google.android.material:material:1.7.0"             # https://mvnrepository.com/artifact/com.google.android.material/material?repo=google
threetenabp = "com.jakewharton.threetenabp:threetenabp:1.4.4"       # https://mvnrepository.com/artifact/com.jakewharton.threetenabp/threetenabp
protobuf-javalite = "com.google.protobuf:protobuf-javalite:3.21.5"  # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-javalite
playServices-wearable = "com.google.android.gms:play-services-wearable:18.0.0" # https://mvnrepository.com/artifact/com.google.android.gms/play-services-wearable

lottie-compose = "com.airbnb.android:lottie-compose:5.2.0" # https://github.com/airbnb/lottie-android
