[versions]
targetSdk = "31"
compileSdk = "31"
minSdk = "21"
wearMinSdk = "25"

kotlin = "1.6.21"
agp = "7.2.0"
realm = "0.11.1"
detekt = "1.20.0"

compose = "1.2.0-beta01"
wearCompose = "1.0.0-beta01"
coroutines = "1.6.1-native-mt"
datastore = "1.0.0"
koin = "3.2.0"
lifecycle = "2.4.1"
core = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/core
glance = "1.0.0-alpha03" # https://developer.android.com/jetpack/androidx/releases/glance

[libraries]
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
realmGradle = { module = "io.realm.kotlin:gradle-plugin", version.ref = "realm" }
detektGradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

realmKotlin = { module = "io.realm.kotlin:library-base", version.ref = "realm" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
#compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material = "androidx.compose.material3:material3:1.0.0-alpha11"
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

compose-activity = "androidx.activity:activity-compose:1.4.0"
compose-constraint = "androidx.constraintlayout:constraintlayout-compose:1.0.0" # https://developer.android.com/jetpack/androidx/releases/constraintlayout

compose-uiTest = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-uiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

composeWear-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearCompose" }
composeWear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearCompose" }
composeWear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearCompose" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines"}

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "core" }

glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
#glance-wear-tiles = { module = "androidx.glance:glance-wear-tiles", version.ref = "glance" }


androidx-annotation = "androidx.annotation:annotation:1.3.0"        # https://mvnrepository.com/artifact/androidx.annotation/annotation
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"           # https://developer.android.com/jetpack/androidx/releases/appcompat
androidx-wear = "androidx.wear:wear:1.2.0"                          # https://developer.android.com/jetpack/androidx/releases/wear
junit = "junit:junit:4.13.2"
material = "com.google.android.material:material:1.6.0"             # https://mvnrepository.com/artifact/com.google.android.material/material?repo=google
threetenabp = "com.jakewharton.threetenabp:threetenabp:1.4.0"       # https://mvnrepository.com/artifact/com.jakewharton.threetenabp/threetenabp/1.4.0
protobuf-javalite = "com.google.protobuf:protobuf-javalite:3.20.1"  # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-javalite
playServices-wearable = "com.google.android.gms:play-services-wearable:17.1.0" # https://mvnrepository.com/artifact/com.google.android.gms/play-services-wearable
