name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'
    - name: Detekt
      run: make detekt
    - name: Build App Gradle
      run: make buildApp
    - name: Build Wear Gradle
      run: make buildWear
