name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Detekt
      run: make detekt
    - name: Build App Gradle
      run: make buildApp
    - name: Build Wear Gradle
      run: make buildWear
